### ISSUE TITLE
The timezone is not used in bar graph

### ISSUE THREAD

**Issue by darold** [dalibo/pgbadger#352] opened 2017-07-28 13:53 UTC
The timezone specified using -Z option is not taken in account in bar graph rendered by detail button.

Also it could be useful to have an other option to specified the timezone of a pgbouncer file when it is different from the one used in the PostgreSQL log file. For example : `--pgbouncer-timezone`

**Comment by bersace** [comment] 2017-09-08 07:24
Is this issue a duplicate of #346 ?

**Comment by darold** [comment] 2017-09-10 13:47
No, here this is a bug describe in the first sentence of the first note. The other issue is about changing on the fly the timezone of the timestamp stored in the log file. If I understand well the log files use the timezone  of the server and the user wants to get date reported at its own timezone. pgBadger allow change of timezone for the graphics but all other dates are retrieved with the timezone of the server.

**Comment by julmon** [comment] 2018-06-07 07:07
@darold https://github.com/dalibo/pgbadger/pull/399 applies timezone offset to pgbouncer logs too with `--log-timezone`

**Comment by julmon** [comment] 2018-06-09 14:14
#414 should fix it

**Closed** 2018-06-12 12:00 UTC
Labels: bug, in progress
