### ISSUE TITLE
Locks --> "No Dataset"

### ISSUE THREAD

**Issue by MichaelDBA** [dalibo/pgbadger#314] opened 2016-11-18 22:32 UTC
PG version 9.4.10 on linux debian wheezy

Not getting anything for locks and Im getting a lot of locking notifications in pg log file.
Here are my 2  log formats:
log_line_prefix = '%m %u@%d[%p:%i] %r %a : '
log_line_prefix = '%m %u@%d[%p:%i] %r %a %e tx:%x : '

log_min_duration_statement = 5 
log_checkpoints = on
log_connections = on
log_disconnections = on
log_duration = off
log_lock_waits = on
log_statement = 'ddl' 
log_temp_files = 0

**Comment by darold** [comment] 2016-11-19 07:59
Hi,

Yes last version of pgbadger now shows information about "*still waiting for" locks in events reports. This is just LOG level entry so nothing critical but this can indicates some poor performances on I/O. Older versions was not reporting this information.

Regards,

**Comment by MichaelDBA** [comment] 2016-12-08 19:08
We still are not able to see any kind of locks even though we have upgraded to pgbadger 9.0.
Here is our prefix: --prefix '%m %u@%d[%p:%i] %r %a %e tx:%x : '
Here are some snippets about what we have in our logs:
```
2016-12-08 00:00:00.686 CST me@mydb[19251:SELECT waiting] 10.2.2.2(38741) B::Backend::Job::AppraiserStatisticsCollector 00000 tx:0 : LOG:  process 19251 still waiting for ShareLock on transaction 3192497977 after 1000.097 ms
2016-12-08 00:00:00.873 CST me@mydb[19251:SELECT waiting] 10.2.2.2(38741) B::Backend::Job::AppraiserStatisticsCollector 00000 tx:0 : LOG:  process 19251 acquired ShareLock on transaction 3192497977 after 1187.200 ms
```

**Comment by darold** [comment] 2016-12-12 09:44
You might have a LOG and STATEMENT entries for a lock to be reported in the Locks reports. For example:
```
2016-09-25 13:17:55 CEST [8536]: [6-1] user=me,db=postgres LOG:  process 8536 acquired ShareLock on transaction 1187 after 5007.510 ms
2016-09-25 13:17:55 CEST [8536]: [7-1] user=me,db=postgres STATEMENT:  SELECT * FROM users FOR UPDATE;
```
They are also reported in the Most frequent events reports.

**Comment by MichaelDBA** [comment] 2016-12-13 18:15
So not quite understanding your response.  I still see no locking stuff in any of the places you mentioned.

**Comment by MichaelDBA** [comment] 2017-01-07 11:43
Is there anything wrong with my input log_line_prefix?
'%m %u@%d[%p:%i] %r %a %e tx:%x : '

**Comment by darold** [comment] 2017-01-07 18:00
It should not. Please send to my private email < gilles AT darold DOT net > a part of you log so that I will be able to reproduce your issue. Add your pgbadger command too.

**Comment by MichaelDBA** [comment] 2017-01-09 12:10
Hi Darold,

I sent you the log snippet for a specific transaction that contains the locking information:
1. waiting for lock info, and
2. got the lock info.

**Comment by darold** [comment] 2017-01-09 13:16
Hi Michael,

Thanks for the log. There's two things that was breaking the parser, the first one is that the %i placeholder must allow the space character, this is now fixed in last commit 870eec. The second think is that you must provide the right prefix otherwise pgbadger will not works as expected. Here, following the log you've sent to me, the prefix must be something like:

    '%m %u@%d[%p:%i] %r [%a] %e tx:%x : '

I'm not sure of the %a placeholfer because in the log it always appears as `[unknown]`, maybe this is an other information like %h but with this prefix and the last commit everything is as expected.

Best regards,

**Comment by MichaelDBA** [comment] 2017-01-10 12:19
You said this would work in the new commit:
'%m %u@%d[%p:%i] %r [%a] %e tx:%x : '

For the current deployed version, you said the %i placeholder must allow the space character.  Where?  Before or After?
before? --> '%m %u@%d[%p: %i] %r [%a] %e tx:%x : '
after?    --> '%m %u@%d[%p:%i ] %r [%a] %e tx:%x : '

**Comment by darold** [comment] 2017-01-11 07:56
You just have to update pgbadger to the last development code, I have fixed the %i placeholder, and  use the given prefix in you pgbadger command line:

    pgbadger --prefix='%m %u@%d[%p:%i] %r [%a] %e tx:%x : ' ...

**Comment by MichaelDBA** [comment] 2017-01-11 14:47
Yes, but my question was if I do not update to the latest version, it appears from your comments that all I have to do is add a space before or after the "%i" placeholder.  So my question is before or after or both?

**Comment by darold** [comment] 2017-01-11 14:53
Yes but update is not an option in your case :-) Adding a space before or after will not help at all, the problem is internal to pgbadger in the way it parse the real value of the placeholder, actually it doesn't expect to find a space character in this value.

**Comment by darold** [comment] 2017-01-11 14:57
uIf you can not update now but you can modifiy pgbadger on the server, you can apply the simple change produced in commit 870eec7 where the `\s` have been appended to the regex.

**Closed** 2017-01-12 14:52 UTC
